# Generated by Django 6.1.1 on 2026-09-06 18:54

import django.db.models.deletion
import django.utils.timezone
import django_pyoidc_keycloak.managers
import django_pyoidc_keycloak.tokens.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_pyoidc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Grants every permission without consulting the authorization backend.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_id', models.UUIDField(blank=True, db_index=True, help_text="The Keycloak 'sub'. Empty means a local account that synchronisation ignores.", null=True, unique=True, verbose_name='Keycloak ID')),
                ('username', models.CharField(help_text="Derived from Keycloak's preferred_username, with a suffix if that name is taken.", max_length=150, unique=True, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('is_active', models.BooleanField(default=True, help_text="Mirrors Keycloak's 'enabled' flag for managed users.", verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether this user may enter the admin site.', verbose_name='staff status')),
                ('keycloak_attributes', models.JSONField(blank=True, default=dict, verbose_name='Keycloak attributes')),
                ('date_joined', models.DateTimeField(blank=True, null=True, verbose_name='date joined')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synchronised')),
                ('is_anonymized', models.BooleanField(default=False, help_text='Set when the Keycloak account was deleted but local data could not be removed.', verbose_name='anonymised')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'keycloak_user',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django_pyoidc_keycloak.managers.KeycloakUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('events', 'Event poll'), ('reconcile', 'Full reconciliation'), ('manual', 'Manual'), ('login', 'Login')], max_length=16, verbose_name='kind')),
                ('realm', models.CharField(max_length=255, verbose_name='realm')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='created')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='updated')),
                ('deleted', models.PositiveIntegerField(default=0, verbose_name='deleted')),
                ('anonymized', models.PositiveIntegerField(default=0, verbose_name='anonymised')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='skipped')),
                ('errors', models.PositiveIntegerField(default=0, verbose_name='errors')),
                ('error_detail', models.TextField(blank=True, verbose_name='error detail')),
            ],
            options={
                'verbose_name': 'synchronisation run',
                'verbose_name_plural': 'synchronisation runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KeycloakGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_id', models.UUIDField(blank=True, db_index=True, help_text='Empty for groups created locally in the admin.', null=True, unique=True, verbose_name='Keycloak ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('path', models.CharField(help_text="Keycloak's full group path, for example /staff/support.", max_length=1000, unique=True, verbose_name='path')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('keycloak_attributes', models.JSONField(blank=True, default=dict, verbose_name='Keycloak attributes')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synchronised')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='keycloak.keycloakgroup', verbose_name='parent group')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'keycloak_group',
                'ordering': ['path'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('keycloak', 'Keycloak'), ('manual', 'Manual override')], default='keycloak', max_length=16, verbose_name='source')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Only for manual overrides. Empty means it does not expire.', null=True, verbose_name='expires at')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='keycloak.keycloakgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'group membership',
                'verbose_name_plural': 'group memberships',
                'db_table': 'keycloak_group_membership',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='keycloakuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Group membership, mirrored from Keycloak. Grants no permission by itself.', related_name='users', through='keycloak.GroupMembership', through_fields=('user', 'group'), to='keycloak.keycloakgroup', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='OIDCTokenSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', django_pyoidc_keycloak.tokens.fields.EncryptedTokenField(blank=True, null=True, verbose_name='access token')),
                ('id_token', django_pyoidc_keycloak.tokens.fields.EncryptedTokenField(blank=True, null=True, verbose_name='ID token')),
                ('refresh_token', django_pyoidc_keycloak.tokens.fields.EncryptedTokenField(blank=True, null=True, verbose_name='refresh token')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='access token expires at')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='refresh token expires at')),
                ('is_offline', models.BooleanField(default=False, help_text='Set when offline_access was requested, so the token outlives the SSO session.', verbose_name='offline session')),
                ('scope', models.CharField(blank=True, max_length=500, verbose_name='scope')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_set', to='django_pyoidc.oidcsession', verbose_name='OIDC session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_sets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'OIDC token set',
                'verbose_name_plural': 'OIDC token sets',
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('realm', models.CharField(max_length=255, verbose_name='realm')),
                ('stream', models.CharField(max_length=32, verbose_name='stream')),
                ('last_event_time', models.DateTimeField(blank=True, null=True, verbose_name='last event time')),
                ('seen_event_ids', models.JSONField(blank=True, default=list, verbose_name='recently seen events')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'synchronisation cursor',
                'verbose_name_plural': 'synchronisation cursors',
                'constraints': [models.UniqueConstraint(fields=('realm', 'stream'), name='keycloak_synccursor_unique_stream')],
            },
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='keycloak_groupmembership_unique_membership'),
        ),
    ]
