# Generated by Django 6.1.1 on 2026-09-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='source',
            field=models.CharField(choices=[('keycloak', 'Keycloak'), ('manual', 'Manual override')], default='manual', max_length=16, verbose_name='source'),
        ),
    ]
