# Generated by Django 6.1.1 on 2026-09-19 08:34

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak', '0002_alter_groupmembership_source'),
        # RoleAssignment below points at AUTH_USER_MODEL; see 0001_initial.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='keycloakgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 19, 8, 34, 35, 606065, tzinfo=datetime.timezone.utc), verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keycloakgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='keycloakuser',
            name='authorization_synced_at',
            field=models.DateTimeField(blank=True, help_text='When group membership, role assignments and the staff flags were last taken from Keycloak. A login whose token was issued before this leaves them alone.', null=True, verbose_name='authorization synchronised'),
        ),
        migrations.AddField(
            model_name='keycloakuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 19, 8, 34, 35, 606199, tzinfo=datetime.timezone.utc), verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keycloakuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='keycloakgroup',
            name='keycloak_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Empty for rows created locally in the admin.', null=True, unique=True, verbose_name='Keycloak ID'),
        ),
        migrations.CreateModel(
            name='KeycloakRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('keycloak_id', models.UUIDField(blank=True, db_index=True, help_text='Empty for rows created locally in the admin.', null=True, unique=True, verbose_name='Keycloak ID')),
                ('keycloak_attributes', models.JSONField(blank=True, default=dict, verbose_name='Keycloak attributes')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synchronised')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('client_id', models.CharField(blank=True, default='', help_text='The Keycloak client this role belongs to. Empty for a realm role.', max_length=255, verbose_name='client')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('composite', models.BooleanField(default=False, verbose_name='composite')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'keycloak_role',
                'ordering': ['client_id', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('client_id', 'name'), name='keycloak_keycloakrole_unique_role')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.CharField(choices=[('keycloak', 'Keycloak'), ('manual', 'Manual override')], default='manual', max_length=16, verbose_name='source')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Only for manual overrides. Empty means it does not expire.', null=True, verbose_name='expires at')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='keycloak.keycloakrole', verbose_name='role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'role assignment',
                'verbose_name_plural': 'role assignments',
                'db_table': 'keycloak_role_assignment',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='keycloakuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Realm and client roles, mirrored from Keycloak. Grants no permission by itself.', related_name='users', through='keycloak.RoleAssignment', through_fields=('user', 'role'), to='keycloak.keycloakrole', verbose_name='roles'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='keycloak_roleassignment_unique_assignment'),
        ),
    ]
